apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: "2.16.2"
    releaseName: sealed-secrets
    namespace: kube-system
    valuesInline:
      # kubeseal CLI가 기본으로 찾는 이름으로 고정
      fullnameOverride: sealed-secrets-controller

      # ARM64 k3s 대응
      image:
        pullPolicy: IfNotPresent

      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi