apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - helmchartconfig.yaml
  - middleware-ipallowlist.yaml   # 공유 IP allowlist (전체 앱에서 참조)
  - ingressroute.yaml
