---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-dns-token
  namespace: kube-system
spec:
  encryptedData:
    token: AgCKjeCt6G/lR3LDz+u8SjhW/k75Fd+VSp9u/K8lz37mFZN8WwgNMGQS+cmCywj9l4RIjDxSTvjdBDV0NL2R3E32mwSfkH93SCTbi8pVJwQ7M4PX3XFbOIQjDBMsRy8zvQcFgKCmkQK8O2sMesMAsZ8ARZ6aU52w6cFm12ps+oxdmqAzDjegJH6ZaYneJ6illUlgdN3ruz+Gd3crvIh4uN5Mp1WE3DzZTrDH5d1rU+JzhtBizHxV+eGo0/Uu6hTw7QaP3JunpVDbMdAYx/nbkElJbYaUXO4qAByMnrLbw7hombwBdwh1O9VVqOPwAm+LWdPLpTSKgRGfLOpI+TlFdiUIrQNXP77he67UThfiwhw5aLF+qNQuVYPTCDeyLRxwsNCClDhSdpyw/5mkWWgooVg2DmBhVMGchyAbaD+9qKksvWSrEJmLXJhJv3fEi6Mxt/Z/LyaVIax6IsQmTJy0nuP7eE/lPg8w9Lk5J/XIlyZho+CXlkHH0zfIrG4ipw2GcCY9e4AW8zXyvPXoJbat+mz6GFa15fZsjO17LWwGBVPYcoDWWkRG4xEo1IVvBYuBYDgZhdLV2DjQVkuh+ICLJiX/hVA+KeaC2NOfgUHa7jqPhNijUOtAMOy/z2Jah5ERKYAh3a7hzbfeDHgn5eWgWv3CHiZJzpMYT56tVWoVi77EIz9E6dGIip96t4ftqUR6NkklThDwYpTPXRVXWTtjLZLeoKYSFOnsfG9m9c7uq8dEvt3mKATaee3wTZGi+HF26CHlgzve+g==
  template:
    metadata:
      name: cloudflare-dns-token
      namespace: kube-system
