---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: browserless-token
  namespace: browserless
spec:
  encryptedData:
    token: AgDeWpSkra/cKsxZA0Dp10wUrD/vK8dtdsi1VSIKfN5ke8sC9I7gv6UqfUfEeVUc8OMTb2ev5/6gFjOfj8wmP8vEi+r6ZgdVI0dODeFCylBbgWH/AdPvn0GgkSmQzvryvebzg0kmuT1MfplmL/8mOz3QEcsgM/zGU8PQn82ZvkKpTgtk4cRk71q3sRulvsT0CCA/6HTgFKEiEAOrruwuFDPObLwVQMSI4/w8S7UOechvUtFtsmUprO5GLy2dYeYaMgpTihtTu2zGyNUv6r0Y0Zkm/hbxJEu7lenV4ORDN7sWpCt9sScjLcgFYSjrYrGeRVm0lBMExmLdUPlz4ku8dDpQcoqaJ/cFqmtojAOEFXaqwPeda092rDs/cLnUYlPAyM1zf6GzFMyiLYByKESw9Nj4htSJLScMf1f1fqbGq4Pc+Fd1Yuo8HR27hsU7C3iXvacN4B98W5NDkIzWdLRZGEwFukzi8p6Mrfpm8AzrXyefWmjwTxMCaS+JL2LGHLyDZk55aTqx68HwJuuKhi9Qq2rj6Az0rdMbiNNquiFpCT4ZuZAT3pEMQRWYiytuzLkOCLpwSoqabfJtwikYKZACuWUyQZyKjFzsBGloSosSlJwqgpgXCjmzGfhPgUGnObHUkoY81IrCRb4hpR5RMZsEnmmTYD8+LTiTDaILHRnvQWqFYZ7xzx83Cyq3liltND9m8ZCKWkbhpfNCHLgIE+xwlFuSady/mppg0w8O35+z
  template:
    metadata:
      name: browserless-token
      namespace: browserless